### ISSUE TITLE
Design: Update our UI Icons to use a 2px border

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol-assets#16]
Current Icon
![image](https://user-images.githubusercontent.com/5924575/44419109-20f87580-a52f-11e8-92c4-c6aea37ec56f.png)
![image](https://user-images.githubusercontent.com/5924575/44423236-78e8a980-a53a-11e8-8c8a-15a1d1b06c93.png)

Updated Icons
![image](https://user-images.githubusercontent.com/5924575/44423193-4939a180-a53a-11e8-8b8b-04a823d655a7.png)

**Comment by stephaniehobson** [comment]
Not sure what this means or if it was done in #22 or not. Closing.
