### ISSUE TITLE
Add Firefox Monitor Logo

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol-assets#19]
There are new logos for Firefox and it's related products we need to upload those logos in to this repository and come up with a roll out plan for getting those logos introduced to consumers. 

The first of these logos, Firefox Monitor, is ready to add to the system.

https://blog.mozilla.org/opendesign/evolving-the-firefox-brand/

**Comment by stephaniehobson** [comment]
Closing in favour of #35.
