### ISSUE TITLE
Add larger logo assets

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol-assets#32]
Currently browser icons are bundled as 200x200px (high-res) and 100x100px (low-res) variants, but it would be good to also provide an additional larger variation that web pages can use. Something along the lines of:

- browser.png (100x100px)
- browser-high-res.png (200x200px)
- browser-large.png (300x300px)
- browser-large-high-res.png (600x600px)

**Comment by stephaniehobson** [comment]
Add to the list, format & sizes needed for favicons:

- ICO 16px & 32px
- PNG 16px
- PNG 32px
- PNG 180px
- PNG 196px

References
https://realfavicongenerator.net/
https://stackoverflow.com/a/48969053/462195
https://www.emergeinteractive.com/insights/detail/The-Essentials-of-FavIcons/

**Comment by stephaniehobson** [comment]
Here is a list of sizes already in use on bedrock, rounded to be divisible by 16 (this matches the grid we use in Protocol currently).

96
128
160
196
256
320

**Comment by stephaniehobson** [comment]
So I guess I'm suggesting:

## ICO
- 16px & 32px

## PNG
- 16px
- 32px
- 96px
- 128px
- 160px
- 180px
- 196px
- 256px

## SVG
- for use over 256px, need to set a default size in the SVG to avoid it taking over the whole screen when there's no size declared. Maybe.... 256px?

**Comment by stephaniehobson** [comment]
This is complicated by the vertically stacked logos with wordmarks:

![firefox-browser-wordmark-vertical-stacked](https://user-images.githubusercontent.com/854701/64718705-9a853d80-d47b-11e9-9854-4c3ee8f7470b.png)

I think the path I want to go with this is that the Firefox logo will be 256px but the image height will be more than this to accommodate the wordmark.

**Comment by stephaniehobson** [comment]
The team discussed it and we would rather people use the assets to generate their own favicons, than to provide them as part of this repo.

That makes the new suggested sizes:

## PNG
- 48px
- 64px
- 96px
- 128px
- 160px
- 196px

## SVG
- for use above 196px, need to set a default size in the SVG to avoid it taking over the whole screen when there's no size declared. I suggest 256px?
