### ISSUE TITLE
Add social sharing page images

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol-assets#33]
In bedrock we include common branded page images for social sharing. It would be good to standardize these and perhaps this is the best place for that? 

![image](https://user-images.githubusercontent.com/400117/64033244-f4b10500-cb43-11e9-9765-fdef8bd8aa02.png)

**Comment by stephaniehobson** [comment]
I agree. This is part of my H2 goal and will be talking with Stephen Horlander about it.

**Comment by stephaniehobson** [comment]
Closing in favour of #8
