### ISSUE TITLE
Support favicon sizes

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol-assets#7]
We need to determine what size favicons to support (this includes things like apple-touch-icon) and then create assets sized to those dimensions.

Ideally we would then ask designers to pick from one of these available sizes to reduce the amount of files we would have to support.

Here's a favicon cheatsheet: https://github.com/audreyr/favicon-cheat-sheet

This is a screenshot of what we currently support:
![image](https://user-images.githubusercontent.com/5924575/42338955-61c07d38-8040-11e8-835d-927466e9077f.png)

**Comment by stephaniehobson** [comment]
I recommend we use these sizes: https://realfavicongenerator.net/faq

**Comment by stephaniehobson** [comment]
Bedrock is currently just serving the largest iOS size and letting the device re-size on its own.

**Comment by stephaniehobson** [comment]
On second thought, I'm going to de-couple this from the other logo work I'm doing and we can address favicons specifically in some other way.

**Comment by stephaniehobson** [comment]
The team discussed it and we would rather people use the assets to generate their own favicons, than to provide them as part of this repo.
