### ISSUE TITLE
Pocket logo-word-hor-white.svg should have white chevron

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/protocol-assets#71]
Currently, it is transparent and this goes against brand guidelines on dark backgrounds (note: this is only applicable when using coral brandmark, monochrome logos do not need white chevron)
<img width="689" alt="Screen Shot 2021-09-23 at 3 44 28 PM" src="https://user-images.githubusercontent.com/19650432/134530086-96827db2-71ee-40fe-930d-2cd761dfcd2f.png">

Brand guidelines: 

<img width="397" alt="Screen Shot 2021-09-23 at 3 50 58 PM" src="https://user-images.githubusercontent.com/19650432/134530473-a45cf295-af9d-4e96-aec9-d25feeaf4b29.png">

**Comment by Ayushsunny** [comment]
Hello @maureenlholland I would like to give a try on this

**Comment by reemhamz** [comment]
Sorry @Ayushsunny! I only saw your comment after we closed the ticket. Please feel free to let us know which tickets you'd want. I'll make sure to double check this time, your contributions have been valuable to us at Mozilla 🎉

**Comment by Ayushsunny** [comment]
Hey @maureenlholland Don't be, please.
Actually, you both are so helping and I want to keep contributing and this was not the last issue of Mozilla tho.
